dist: xenial

language: node_js

addons:
  apt:
    packages:
      - chromium-browser

node_js:
  - lts/*
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - NODE_OPTIONS=--max_old_space_size=4096 yarn lint
  - yarn audit
  - NODE_OPTIONS=--max_old_space_size=4096 yarn test --code-coverage
  - NODE_OPTIONS=--max_old_space_size=4096 yarn build

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
